### ISSUE TITLE
can't get this to work

### ISSUE THREAD

**Issue by jmls** [borntorun/angular-jssignals#1]
I know I must be doing something stupid

in my run function, I have

``` javascript
  function runBlock($state, $rootScope,SignalsService) {
    $rootScope.$state = $state;
console.log("registered");
    SignalsService.register('foobar');
 }
```

then in a controller I have

``` javascript
     SignalsService.listen('foobar',(data) => {
            console.log("hurrah",data);
        });
```

and in another, I have

``` javascript
console.log("sending");
SignalsService.emit('foobar',{working:false});
```

so in my console, I get "registered" followed by "sending" but never get a "hurrah" :(

what am I missing ?

**Comment by borntorun** [comment]
Hi

Dynamic registration (after SignalsService is created )is not yet possible; you have to set all signals in SignalsServiceProvider before use the SignalsService; like this:

```
//in a config block of your module
SignalsServiceProvider.config({
    init: true, //register is automatic dont need to call register method
    signals: {
        foobar: 'foobar'
    }
});
```

And then in the rest of your code:

```
SignalsService.foobar.emit({working:false}); // note the use the signal name as a key

SignalsService.foobar.listen(() => {
....
});
```

(I have a [TODO ](https://github.com/borntorun/angular-jssignals/blob/66bddd53e1c90536ddf714c4e0d329a3718d1a03/src/angular-jssignals.js#L261)in the code antecipating this situation... :-) )

I hope this help.
Thanks (and sorry for the late answer)

**Comment by borntorun** [comment]
@jmls Hope you've solved your issue. Closing this. Thanks.
